In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [4]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [14]:
X=df.drop(columns=['Survived'])
Y=df['Survived']
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
X_train['Age_imputed']=X_train['Age']
X_test
X_test['Age_imputed']=X_test['Age']
X_train

      Age     Fare  Age_imputed
140   NaN  15.2458          NaN
439  31.0  10.5000         31.0
817  31.0  37.0042         31.0
378  20.0   4.0125         20.0
491  21.0   7.2500         21.0
..    ...      ...          ...
835  39.0  83.1583         39.0
192  19.0   7.8542         19.0
629   NaN   7.7333          NaN
559  36.0  17.4000         36.0
684  60.0  39.0000         60.0

[712 rows x 3 columns]

In [15]:
X_train['Age_imputed'][X_train['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values
X_test['Age_imputed'][X_test['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_test['Age'].isnull().sum()).values

C:\Users\karan\AppData\Local\Temp\ipykernel_20384\3090101260.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_train['Age_imputed'][X_train['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values
C:\Users\karan\AppData\Local\Temp\ipykernel_20384\3090101260.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_test['Age_imputed'][X_test['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_test['Age'].isnull().sum()).values

In [16]:
print('Original variable variance: ', X_train['Age'].var())
print('Variance after random imputation: ', X_train['Age_imputed'].var())

Original variable variance:  213.7165085187578
Variance after random imputation:  216.18272797294517

In [ ]:
X_train[['Fare', 'Age', 'Age_imputed']].cov()#use random state in prooduction site to make sure random variable is same

                    Fare         Age  Age_imputed
Fare         2513.549265   79.072379    55.113262
Age            79.072379  213.716509   213.716509
Age_imputed    55.113262  213.716509   216.182728

In [ ]:
# FOR MISSING INDICATOR TECHNIQUE USE add_indicator=true on algorithum bss